---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: application-samples
spec:
  type: GitHub
  pathname: https://github.com/jnpacker/application-samples.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops-fleet-samples
  namespace: big-bang
spec:
  pathname: https://github.com/jnpacker/gitops-fleet-samples.git
  type: Git