apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-sample
  namespace: argocd
spec:
  generators:
  - clusters: {} # This is a generator, specifically, a cluster generator.
    #  selector:
    #    matchLabels:
    #      usage: development
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'nginx-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/jnpacker/application-samples/
        targetRevision: main
        path: nginx
      destination:
        server: '{{server}}'
        namespace: nginx-sample
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true