apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: policy

resources:
- namespace.yaml
- etcd-encryption.yaml
- openshift-gitops.yaml
#- imagemanifestvulnerability.yaml
- complianceoperator.yaml
- placement.yaml
