---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: infrastructure-buildout
  name: openshift-gitops-applicationset-controller2
  namespace: openshift-gitops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-gitops-applicationset-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openshift-gitops-applicationset-controller
    spec:
      containers:
        - command:
            - applicationset-controller
            - '--argocd-repo-server'
            - >-
              openshift-gitops-repo-server.openshift-gitops.svc.cluster.local:8081
          image: quay.io/jpacker/argocd-applicationset:0.3.1
          imagePullPolicy: Always
          name: argocd-applicationset-controller
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: openshift-gitops-applicationset-controller
      serviceAccount: openshift-gitops-applicationset-controller
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-applicationset-controller-placement
  namespace: openshift-gitops
rules:
- apiGroups:
  - apps.open-cluster-management.io
  - cluster.open-cluster-management.io
  resources:
  - placementrules
  - placementdecisions
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-applicationset-controller-placement
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-applicationset-controller-placement
subjects:
- kind: ServiceAccount
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops
